### ISSUE TITLE
Test errors on master

### ISSUE THREAD

**Issue by brgillis** [GalSim-developers/GalSim#861] opened 2017-01-31 16:11 UTC
A few tests are failing or throwing errors for me on master, when run on my own computer. I've attached the log of running these tests: [test_failures.txt](https://github.com/GalSim-developers/GalSim/files/742485/test_failures.txt)

I'm using Python v2.7.9, numpy v1.8.2, and astropy v1.0.3 (let me know if any other dependency versions will help).

**Comment by rmjarvis** [comment] 2017-01-31 19:14
Try branch '#861'.  I don't think any of the changes I made will have fixed the problem (although one of them could conceivably have fixed it).  But since I can't reproduce what you're seeing, it's hard to say.  I did add some output that should help us diagnose what is going on though, so send that if it still fails.

**Comment by brgillis** [comment] 2017-02-02 02:16
Here's the updated output from this branch: [test_failures.txt](https://github.com/GalSim-developers/GalSim/files/746674/test_failures.txt)

**Comment by rmjarvis** [comment] 2017-02-02 15:08
So, for some reason, your version of numpy is not respecting the command `np.set_printoptions(threshold=np.inf)`, which is supposed to prevent it from doing all those `...` in the array reprs.  I'm not sure that figuring out a workaround for this is the best use of my time.  

Any chance you can just upgrade your numpy version?  It's pretty easy to do.  `pip install -U numpy`.  Add `--user` if you don't have root privileges.

**Comment by brgillis** [comment] 2017-02-02 17:29
I tried upgrading numpy (to 1.12.0), but it didn't solve this issue. I dug into it a bit, and it seems that this issue with np.set_printoptions only comes up after astropy is imported - it seems something astropy is doing overrides any printoptions changes by numpy. Once I upgraded astropy (to 1.3), this part started working properly, but I got some other failures now (along with plenty of deprecation warnings): 
[test_failures.txt](https://github.com/GalSim-developers/GalSim/files/748507/test_failures.txt)

**Comment by jmeyers314** [comment] 2017-02-02 18:41
@brgillis , did you re-pull master in the last 24 hours?  (or re-merge master into this branch, I suppose?)  I think I addressed all the "floats cannot be ints" deprecations when I merged the py3urllib branch yesterday.

**Comment by rmjarvis** [comment] 2017-02-03 04:36
@jmeyers314 I merged that in to this branch, so that's taken care of.

Of course, as usual, the latest version of astropy is kind of a disaster.  Working on putting out those fires now...

(e.g. [clobber is now overwrite](https://github.com/astropy/astropy/pull/5171) WTF was that for?!!!)

**Comment by rmjarvis** [comment] 2017-02-03 05:37
OK, it's not as bad as I thought.  Fixing that deprecation warning (by just avoiding it and implementing the file removal ourselves) got rid of a pile of other deprecations that had showed up on my machine.  I think somewhere in the astropy deprecation handling they use deprecated features of IPython.  (Yes, seriously!)  But once they aren't issuing their own deprecation warning, those other ones also went away.

The failures Bryan got seem to be due to a numpy change in version 1.12 that `np.roll` doesn't always come back with a C-contiguous array as it had in <=1.11.  But it's easy enough to force it.  

I think this branch should work for you now.

**Comment by rmjarvis** [comment] 2017-02-16 00:34
Fixed via #862

**Closed by rmjarvis** 2017-02-16 00:34 UTC
Labels: tests
