### ISSUE TITLE
Unable to install "COSMOS_25.2_training_sample.tar.gz".

### ISSUE THREAD

**Issue by demitri** [GalSim-developers/GalSim#1023] opened 2019-04-15 16:13 UTC
I'm trying to install a training sample with this command:

```
galsim_download_cosmos -s 25.2
```

The downloaded file appears to be incomplete:

```
%  galsim_download_cosmos -s 25.2
Type galsim_download_cosmos -h to see command line options.

Downloading from url:
  http://great3.jb.man.ac.uk/leaderboard/data/public/COSMOS_25.2_training_sample.tar.gz
Target location is:
  /usr/local/anaconda/lib/python3.7/site-packages/galsim/share/COSMOS_25.2_training_sample.tar.gz

Size of COSMOS_25.2_training_sample.tar.gz: 4167 MBytes

Download complete. / 4167 MBytes  [24.63%]
Unpacking the tarball...
COSMOS_25.2_training_sample/ 
COSMOS_25.2_training_sample/acs_I_unrot_sci_20_cf.fits 
COSMOS_25.2_training_sample/README 
COSMOS_25.2_training_sample/real_galaxy_catalog_25.2.fits 
COSMOS_25.2_training_sample/real_galaxy_catalog_25.2_fits.fits 
COSMOS_25.2_training_sample/real_galaxy_catalog_25.2_selection.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n1.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n10.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n11.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n12.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n13.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n14.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n15.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n16.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n17.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n18.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n19.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n2.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n20.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n21.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n22.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n23.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n24.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n25.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n26.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n27.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n28.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n29.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n3.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n30.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n31.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n32.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n33.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n34.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n35.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n36.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n37.fits 
COSMOS_25.2_training_sample/real_galaxy_images_25.2_n38.fits 
Traceback (most recent call last):
  File "/usr/local/anaconda/bin/galsim_download_cosmos", line 11, in <module>
    load_entry_point('GalSim==2.1.4', 'console_scripts', 'galsim_download_cosmos')()
  File "/usr/local/anaconda/lib/python3.7/site-packages/galsim/download_cosmos.py", line 427, in main
    unpack(target, target_dir, unpack_dir, meta, args, logger)
  File "/usr/local/anaconda/lib/python3.7/site-packages/galsim/download_cosmos.py", line 307, in unpack
    tar.list(verbose=False)
  File "/usr/local/anaconda/lib/python3.7/tarfile.py", line 1883, in list
    for tarinfo in members:
  File "/usr/local/anaconda/lib/python3.7/tarfile.py", line 2405, in __iter__
    tarinfo = self.next()
  File "/usr/local/anaconda/lib/python3.7/tarfile.py", line 2281, in next
    self.fileobj.seek(self.offset - 1)
  File "/usr/local/anaconda/lib/python3.7/gzip.py", line 368, in seek
    return self._buffer.seek(offset, whence)
  File "/usr/local/anaconda/lib/python3.7/_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "/usr/local/anaconda/lib/python3.7/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

I tried running the command again to re-download the file but returned with the same error. Is the source file maybe incomplete? This is the file that's downloaded; the size doesn't match what's expected (4167 MBytes).

```
[/usr/local/anaconda/lib/python3.7/site-packages/galsim/share] % ll
total 2102432
-rw-r--r--  1 root  wheel  1076442506 Apr 15 12:08 COSMOS_25.2_training_sample.tar.gz
```

**Comment by demitri** [comment] 2019-04-15 16:37
Update: Since the full URL and intended destination was provided, I tried to download the file manually with wget. This is the result:

```
% wget http://great3.jb.man.ac.uk/leaderboard/data/public/COSMOS_25.2_training_sample.tar.gz
--2019-04-15 12:16:23--  http://great3.jb.man.ac.uk/leaderboard/data/public/COSMOS_25.2_training_sample.tar.gz
Resolving great3.jb.man.ac.uk... 130.88.24.48
Connecting to great3.jb.man.ac.uk|130.88.24.48|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4370425117 (4.1G) [text/plain]
Saving to: 'COSMOS_25.2_training_sample.tar.gz'

COSMOS_25.2_training_sample.ta  24%[===========>                                      ]   1.00G  6.32MB/s    in 3m 13s  

2019-04-15 12:19:38 (5.31 MB/s) - Connection closed at byte 1076502410. Retrying.

--2019-04-15 12:19:39--  (try: 2)  http://great3.jb.man.ac.uk/leaderboard/data/public/COSMOS_25.2_training_sample.tar.gz
Connecting to great3.jb.man.ac.uk|130.88.24.48|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 4370425117 (4.1G), 3293922707 (3.1G) remaining [text/plain]
Saving to: 'COSMOS_25.2_training_sample.tar.gz'

COSMOS_25.2_training_sample.tar.gz    49%[+++++++++++++++++================>                                    ]   2.00G  6.30MB/s    in 3m 23s  

2019-04-15 12:23:02 (5.07 MB/s) - Connection closed at byte 2152939500. Retrying.

--2019-04-15 12:23:04--  (try: 3)  http://great3.jb.man.ac.uk/leaderboard/data/public/COSMOS_25.2_training_sample.tar.gz
Connecting to great3.jb.man.ac.uk|130.88.24.48|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 4370425117 (4.1G), 2217485617 (2.1G) remaining [text/plain]
Saving to: 'COSMOS_25.2_training_sample.tar.gz'

COSMOS_25.2_training_sample.tar.gz    73%[++++++++++++++++++++++++++++++++++================>                   ]   3.01G  6.17MB/s    in 3m 59s  

2019-04-15 12:27:03 (4.30 MB/s) - Connection closed at byte 3229376590. Retrying.

--2019-04-15 12:27:06--  (try: 4)  http://great3.jb.man.ac.uk/leaderboard/data/public/COSMOS_25.2_training_sample.tar.gz
Connecting to great3.jb.man.ac.uk|130.88.24.48|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 4370425117 (4.1G), 1141048527 (1.1G) remaining [text/plain]
Saving to: 'COSMOS_25.2_training_sample.tar.gz'

COSMOS_25.2_training_sample.tar.gz    98%[+++++++++++++++++++++++++++++++++++++++++++++++++++================>  ]   4.01G  4.02MB/s    in 2m 56s  

2019-04-15 12:30:02 (5.83 MB/s) - Connection closed at byte 4305987180. Retrying.

--2019-04-15 12:30:06--  (try: 5)  http://great3.jb.man.ac.uk/leaderboard/data/public/COSMOS_25.2_training_sample.tar.gz
Connecting to great3.jb.man.ac.uk|130.88.24.48|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 4370425117 (4.1G), 64437937 (61M) remaining [text/plain]
Saving to: 'COSMOS_25.2_training_sample.tar.gz'

COSMOS_25.2_training_sample.tar.gz   100%[++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++=>]   4.07G  6.29MB/s    in 12s     

2019-04-15 12:30:19 (5.20 MB/s) - 'COSMOS_25.2_training_sample.tar.gz' saved [4370425117/4370425117]
```

It appears the connection was forcibly(?) closed once 1GB of data was transferred. Maybe there is a setting on the web server that needs to be increased?

**Comment by rmjarvis** [comment] 2019-04-15 17:11
It also seems to have become quite slow.  Slower than I remember this being anyway.  (I haven't gotten up to 1GB yet, but am trying to reproduce this on my machine.)

Anyway, I think maybe we should look into a different place to host this. Especially since @joezuntz isn't even at Manchester anymore...
https://www.cnet.com/how-to/how-to-save-and-share-ridiculously-large-files/

**Comment by rmandelb** [comment] 2019-04-15 17:29
Hmmm, I have room for 1 TB of files through Box (all CMU faculty can do this) and it's possible to share with anybody via a link.  I'm not sure about speed but at least from a storage perspective we could easily put all the training datasets there.  Would you like me to put one there for a cross-comparison of download speed?  Or do you think one of the other options in that link might be preferable?

**Comment by joezuntz** [comment] 2019-04-15 17:29
I could also ask about moving the server up to Edinburgh, that would probably be easier than where it is now.

**Comment by EiffL** [comment] 2019-06-09 08:10
I'm going to point to #1033 for this issue.
I had the same exact problem, turns out the current server only allows for 1GB downloads. It's not a deal breaker, because the download can be resumed and the file downloaded in several steps.... but not with a simple read() call:
https://github.com/GalSim-developers/GalSim/blob/e1636fad691cb33605562c153471be1f065ddc43/galsim/download_cosmos.py#L268

This could be fixed by using urllib.urlretrieve() and something like that: https://stackoverflow.com/questions/31529151/python-3-urllib-urlretrieve-retry-on-download-fail

**Comment by rmjarvis** [comment] 2019-08-03 17:27
This is fixed on master.  cf. #1043

**Closed by rmjarvis** 2019-08-03 17:27 UTC
Labels: bug report, inputs, optimization/performance
