### ISSUE TITLE
Photon shooting for Chromatic objects

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#540] opened 2014-04-29 17:20 UTC
In #535, I updated the drawing routines in chromatic.py to use the new drawImage function, which includes the option to do photon shooting.  I thought this might mean that the chromatic objects would now be rendered correctly with method='phot'.  But thinking more about it, I'm not so sure that the integration stuff is really done correctly when photon shooting.

The right way to do it would be to draw each photon from the SED of the object, scale its flux by the bandpass throughput, and then shoot it onto the image.  At least for separable objects.  It gets more complicated when they aren't separable.

Anyway, this issue is for someone to investigate photon shooting of chromatic objects and make sure it is working correctly (or probably make it work correctly if, as I suspect, it currently isn't).

**Comment by cwwalter** [comment] 2016-04-15 17:21
A Duke student (@jiwonpark93) is going to start to look at this by building up a image chromatically with photon shooting and comparing with the fft results.

**Comment by cwwalter** [comment] 2016-06-23 02:15
A quick recap of @jiwonpark93's work so far on implementing chromatic photon shooting in GalSim. By sampling random numbers from a SED, freezing the chromatic object at that frequency and then shooting photons at each frequency she could reproduce simple FFT convolved cases.   In order to get the normalization to work properly she needs to account for the fact that drawImage wants to preserve the total flux of the chromatic object and scale the SED before shooting appropriately.  A Chi2 test shows the expected agreement for given statistics between the two methods on the resulting 2d objects.

She is now working on comparing more complicated compound objects along with chromatic PSFs etc.  Also, after suggestion from @rmandelb she is refactoring the code to better separate the objects and SEDs to more naturally handle compound objects. After the code works in the python layer, the eventual goal is to migrate it into a fast C++ version.  More progress is expected later in the summer.

**Comment by cwwalter** [comment] 2017-01-02 21:22
I reported on updates to this work by @jiwonpark93 in November, but it was on slack (in the desc-ssim channel) and I think it fell through the cracks a bit because everyone was at the DESC hackweek.  I'm transferring the information to here to get things back on track and to make sure that it is not lost.

------

Ji Won completed a python version of her chromatic photon shooting code as we discussed in this issue above.   It is in:

https://github.com/DukeCosmology/photon-shooting

It is in a slightly different form than we originally discussed (it is in python notebooks) but the skeleton for the code that should be translated into C++ now exists.  Basically this code repeatedly freezes a chromatic object as samples by a SED and then does monochromatic photon shooting from the frozen object thereby building up proper chromatic photon shot distribution.

She started by validating this with a ChromaticAtmosphere and that was documented in this PDF file:

[final_tests_JWP.pdf](https://github.com/GalSim-developers/GalSim/files/681392/final_tests_JWP.pdf)

Then, after feedback from the people at the hack week in slack she redid the test with a much more chromatic (and less physical) PSF utilizing a shift and dilation as suggested by @jmeyers314 and @rmjarvis.  She added a new notebook with these tests and documented the results in:

[JWP_more_chromatic_psf_tests.pdf](https://github.com/GalSim-developers/GalSim/files/681395/JWP_more_chromatic_psf_tests.pdf)

**Comment by rmjarvis** [comment] 2017-01-02 23:28
This is great.  Thanks Ji Won!

There is one thing I don't really understand about the results you're getting.  I expected the drawn PSFs to be smeared along the direction of the shift (the x direction here).  But they all look very round to me.  Is this just an illusion (it can be hard to identify ellipses by eye) or is the range of wavelengths within the band just too small to have a significant effect?  From how much the spots moved from u band to Y band, I would have thought the single-band smearing effect would be noticeable.

As for implementing this in code, @jmeyers314 has a branch currently in [PR](https://github.com/GalSim-developers/GalSim/pull/847) that involves moving the `shoot` functions up to python.  This should make it much easier to have the chromatic objects implement their own versions of `shoot` using the correct wavelength for each photon.  I think it's likely that most of them can do everything fairly efficiently without resorting to additional C++ code, but we can certainly do that if it seems necessary.

**Comment by jiwonpark93** [comment] 2017-01-03 17:58
Thank you very much for the update! It seems that your second explanation may be right, that the range of wavelengths per band is too small. When I changed the PSF shift to vary more dramatically with wavelength (wave/15 instead of wave/200), the smearing became more noticeable. I compare the u-band and the g-band images in the attached file.
[more_elliptic.pdf](https://github.com/GalSim-developers/GalSim/files/682905/more_elliptic.pdf)

**Comment by rmjarvis** [comment] 2020-09-15 22:21
This is done in PR #1100

**Closed** 2020-10-01 00:43 UTC
Labels: chromatic, desc, feature request
