### ISSUE TITLE
issue building with gcc 5 and Anaconda

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#842] opened 2016-12-06 21:19 UTC
I'm getting an error building for ubuntu 16.04.  I'm using the latest anaconda as of this data
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ImportError: /home/esheldon/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by .sconf_temp/conftest_31_mod/check_tmv.so)
```

Here is the scons output
```
[esheldon@forest GalSim] scons TMV_LINK=/home/esheldon/local/share/tmv/tmv-link TMV_DIR=/home/esheldon/local
scons: Reading SConscript files ...
SCons is version 2.4.1 using python version 2.7.12
Python is from /usr/include/python2.7
Using the following (non-default) scons options:
   TMV_DIR = /home/esheldon/local
   TMV_LINK = /home/esheldon/local/share/tmv/tmv-link
These can be edited directly in the file gs_scons.conf.
Type scons -h for a full list of available options.
Using python =  /home/esheldon/anaconda3/bin/python
Using default PYPREFIX =  /home/esheldon/anaconda3/lib/python3.5/site-packages
Using compiler: /usr/bin/g++
compiler version: 5.4.0
Determined that a good number of jobs = 8
Checking for C++ header file fftw3.h... yes
Checking for correct FFTW linkage... yes
Checking for boost header files... yes
Boost version is 1.58.0
Checking for C++ header file TMV.h... yes
TMV version is 0.73
Using TMV_LINK file: /home/esheldon/local/share/tmv/tmv-link
     -L/home/esheldon/local/lib -ltmv -lblas -lgfortran -lpthread
Checking for correct TMV linkage... (this may take a little while)
Checking for correct TMV linkage... yes
Checking if we can build against Python... yes
Building for python version 3.5
Checking if we can build module using TMV...
Unable to build a python loadable module that uses tmv
```

**Comment by esheldon** [comment] 2016-12-06 21:25
the name of this issue is probably a misnomer, since the problem might actually be related to anaconda shipping a libstdc++ and scons finding that instead of the system one

**Comment by rmjarvis** [comment] 2016-12-06 22:07
Yeah, probably has more to do with anaconda than Ubuntu.  Anaconda have been notoriously problematic for this kind of thing.

Aside: Your TMV_LINK specification is redundant.  You only need to specify TMV_DIR.

**Comment by rmjarvis** [comment] 2016-12-06 22:09
This site might have some helpful advice:
http://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error

**Comment by esheldon** [comment] 2016-12-07 14:31
I think the problem is that somewhere scons, or the SConstruct, has decided to add `/home/esheldon/anaconda3/bin/../lib/` to the link path.  That is not the standard library used by TMV (it used the system one)

**Comment by rmjarvis** [comment] 2016-12-07 16:00
That's probably where libpython*.so lives, so it needs to be there for the loadable module.  TMV worked when it compiled a standalone program.  The failure here is when it's included as part of a python loadable module.

My guess is that you'll either need to recompile TMV to use the anaconda stdc++ library or update the system one to be compatible with it.

**Comment by rmjarvis** [comment] 2016-12-07 16:06
Just to share, we have a system at Penn where anaconda shipped with its own MKL libraries that were incompatible with the ones in the icpc directories, so I had to switch my lib directory for TMV to include .../anaconda/lib so it would find those libraries.  Otherwise I got similar kinds of problems when compiling GalSim.

Seems like bad form to me for Anaconda to be shipping with all these 3rd party libraries, but what else is new...

**Comment by esheldon** [comment] 2016-12-08 19:53
Is that using `EXTRA_LIB_PATH` ?

**Comment by esheldon** [comment] 2016-12-08 20:07
I tried modifying `EXTRA_LIB_PATH` as well as setting my `LD_LIBRARY_PATH` to have the anaconda lib dir.  and in these cases I got a different error

```
[esheldon@forest GalSim] scons TMV_DIR=/home/esheldon/local
scons: Reading SConscript files ...
SCons is version 2.4.1 using python version 2.7.12
Python is from /usr/include/python2.7
Using the following (non-default) scons options:
   TMV_DIR = /home/esheldon/local
These can be edited directly in the file gs_scons.conf.
Type scons -h for a full list of available options.
Using python =  /home/esheldon/anaconda3/bin/python
Using default PYPREFIX =  /home/esheldon/anaconda3/lib/python3.5/site-packages
Using compiler: /usr/bin/g++
compiler version: 5.4.0
Determined that a good number of jobs = 8
Checking for C++ header file fftw3.h... yes
Checking for correct FFTW linkage... yes
Checking for boost header files... yes
Boost version is 1.58.0
Checking for C++ header file TMV.h... yes
TMV version is 0.73
Using TMV_LINK file: /home/esheldon/local/share/tmv/tmv-link
     -L/home/esheldon/anaconda3/lib -L/home/esheldon/local/lib -ltmv -lblas -lgfortran -lpthread
Checking for correct TMV linkage... (this may take a little while)
Checking for correct TMV linkage... 
Error: TMV file failed to link correctly
Check that the correct location is specified for TMV_DIR
```

**Comment by rmjarvis** [comment] 2016-12-11 20:14
I've managed to reproduce this on a system where I installed the Anaconda 4.2.0 and gcc 6.2.0.  The commands that worked for me are:

TMV:

scons PREFIX=~ EXTRA_LIB_PATH=~/anaconda3/lib EXTRA_INCLUDE_PATH=~/anaconda3/include
scons install

GalSim:

scons PREFIX=~ TMV_DIR=~ FFTW_DIR=/usr/local/fftw-3.3
scons install

Without more information, I'm afraid I can't guess why your attempt at using the anaconda path in EXTRA_LIB_PATH didn't work.  Maybe you didn't also add the include path?

**Comment by esheldon** [comment] 2016-12-12 17:48
my gcc is 5.4.0

**Comment by esheldon** [comment] 2016-12-12 17:59
Adding the include, it is still failing at the "Checking for correct TMV linkage..."

**Comment by esheldon** [comment] 2016-12-12 18:01
full log

[config.log.txt](https://github.com/GalSim-developers/GalSim/files/646773/config.log.txt)

**Comment by rmjarvis** [comment] 2016-12-12 18:52
Do the TMV tests compile and run properly?  Because the error you are getting:
```
g++ -o .sconf_temp/conftest_16 .sconf_temp/conftest_16.o -Llib -L/home/esheldon/local/lib -L/home/esheldon/anaconda3/lib -ltmv_symband -lfftw3 -lpthread -ltmv -lblas -lgfortran -lpthread
.sconf_temp/conftest_16.o: In function `void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .isra.33]':
conftest_16.cpp:(.text+0x89): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
.sconf_temp/conftest_16.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
conftest_16.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0x3b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)'
conftest_16.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0x5c): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
conftest_16.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0x6d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
.sconf_temp/conftest_16.o: In function `tmv::FailedAssert::FailedAssert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
conftest_16.cpp:(.text._ZN3tmv12FailedAssertC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmS6_[_ZN3tmv12FailedAssertC5ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmS6_]+0x53): undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `std::runtime_error::runtime_error(std::runtime_error const&)'
/home/esheldon/local/lib/libtmv.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
/home/esheldon/local/lib/libtmv.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_not_of(char const*, unsigned long, unsigned long) const'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()'
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const'
collect2: error: ld returned 1 exit status
```
is prior to anything in GalSim and probably should have failed when compiling the TMV test programs.

It's possible that you may need to upgrade to tmv 0.74 which has support for `-std=c++11` (the default in gcc6, and maybe gcc5).  I think if you were using `-std=c++11`, it might have compiled the library, but the test suite would fail to compile.  Or you can use `EXTRA_FLAGS=-std=c++03` to make it use c++03.  In any case, you should make sure the TMV test suite works first before trying it with GalSim.

**Comment by esheldon** [comment] 2016-12-12 19:39
The tests are failing with the same errors.  I tried adding `EXTRA_FLAGS=-std=c++03` with no luck

**Comment by esheldon** [comment] 2016-12-12 19:43
0.74 also fails tests

**Comment by esheldon** [comment] 2016-12-12 19:50
But if I remove the `EXTRA_LIB_PATH=~/anaconda3/lib EXTRA_INCLUDE_PATH=~/anaconda3/include` it passes

**Comment by rmjarvis** [comment] 2016-12-12 20:06
Then you have an incompatibility between the compiler you're using to compile TMV (and GalSim) and whatever was used to compile Anaconda.  If you can't get TMV to compile with `EXTRA_LIB_PATH=~/anaconda3/lib`, then there is no hope for GalSim to work with that same compiler.

If you want my help diagnosing the problem, you'll need to send me the TMV output showing exactly what you tried and exactly what the errors are.  Just saying 0.74 also failed is hot helpful.

**Comment by esheldon** [comment] 2016-12-12 20:15
OK, I wasn't sure what detail you wanted.  Anaconda is compiled with gcc 4.4.7.  I have 5.4.0

I've attached the output of the following command

`scons tests EXTRA_LIB_PATH=~/anaconda3/lib EXTRA_INCLUDE_PATH=~/anaconda3/include &> compile.txt`

[compile.txt](https://github.com/GalSim-developers/GalSim/files/647069/compile.txt)

**Comment by esheldon** [comment] 2016-12-12 20:35
Here is the output when I include `EXTRA_FLAGS=-std=c++03`

I still see the complaints about `__cxx11::basic_string` and other things, so that flag isn't doing what I think it does

[compile.txt](https://github.com/GalSim-developers/GalSim/files/647133/compile.txt)

**Comment by rmjarvis** [comment] 2016-12-12 20:47
I think you have two options:
1. Upgrade Anaconda to something compatible with gcc5.4.0.  gcc changed their ABI starting in 5.1, so the libstdc++ library from 4.4.7 is not ABI compatible with 5.4.
2. Read [this](https://gcc.gnu.org/onlinedocs/gcc-5.2.0/libstdc++/manual/manual/using_dual_abi.html) and try the suggestions they have there for cross compiling things that cross the 5.1 ABI change.  It's possible that using `EXTRA_FLAGS="-std=c++03 -D_GLIBCXX_USE_CXX11_ABI=0"` will work.  But I've never tried it, so I can't say for sure whether that addresses the problem you're having.

**Comment by esheldon** [comment] 2016-12-12 21:17
Interestingly, using 

`scons tests EXTRA_LIB_PATH=~/anaconda3/lib EXTRA_INCLUDE_PATH=~/anaconda3/include EXTRA_FLAGS="-std=c++03 -D_GLIBCXX_USE_CXX11_ABI=0"` 

then compilation of tmv tests does succeed. but galsim still fails (attached).

I don't know how to get anaconda onto gcc 5, I'm not sure they support that.

[config.log.txt](https://github.com/GalSim-developers/GalSim/files/647222/config.log.txt)

**Comment by rmjarvis** [comment] 2016-12-12 21:22
You need those same EXTRA_FLAGS for GalSim too.

**Comment by esheldon** [comment] 2016-12-12 21:27
Sorry about that.  It still fails, here is the new config (thanks for your patience)

[config.log.txt](https://github.com/GalSim-developers/GalSim/files/647245/config.log.txt)

**Comment by rmjarvis** [comment] 2016-12-12 21:32
Please send me gs.error, rather than config.log.  This doesn't have what I need to further diagnose what is going on.  (Also, make sure you are on the latest GalSim master branch, since I added some diagnostic checks recently that I'll need to look at.)

**Comment by esheldon** [comment] 2016-12-12 21:36
OK, latest master and attaches gs.error (didn't know about that)

[gs.error.txt](https://github.com/GalSim-developers/GalSim/files/647272/gs.error.txt)

**Comment by esheldon** [comment] 2016-12-12 21:39
actually, reading that file I realized I probably needed `EXTRA_LIB_PATH=~/anaconda3/lib EXTRA_INCLUDE_PATH=~/anaconda3/include` for the galsim build too

and it fails differently, so maybe making progress.  see attached gs.error

[gs.error.txt](https://github.com/GalSim-developers/GalSim/files/647280/gs.error.txt)

**Comment by rmjarvis** [comment] 2016-12-12 21:50
```
/home/esheldon/local/lib/libtmv_symband.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
```
Are you sure this is the one that you got working with the `-D_GLIBCXX` bit?  It still has those `__cxx11::basic_string` things in there.  Did you remember to `scons install` it?

**Comment by esheldon** [comment] 2016-12-12 22:07
yeah, that was it.   I had been running `scons test` but forgot to follow it up with `scons install`

it can now compile against tmv.  I also had to install boost via conda to get compatibility.  

Now galsim installs and passes most tests.

To summarize:

1. install boost via conda
2. install tmv, compiling against the standard library furnished by anaconda
3. install galsim with same flags

install boost
`conda install -c anaconda boost=1.61.0`

install tmv
```
scons install EXTRA_LIB_PATH=~/anaconda3/lib EXTRA_INCLUDE_PATH=~/anaconda3/include EXTRA_FLAGS="-std=c++03  -D_GLIBCXX_USE_CXX11_ABI=0"  PREFIX=/home/esheldon/local/
```

install galsim
```
scons install TMV_DIR=/home/esheldon/local/ EXTRA_LIB_PATH=~/anaconda3/lib EXTRA_INCLUDE_PATH=~/anaconda3/include EXTRA_FLAGS="-std=c++03 -D_GLIBCXX_USE_CXX11_ABI=0" PREFIX=/home/esheldon/anaconda3/
```

**Comment by rmjarvis** [comment] 2016-12-12 22:27
Great!  :)

> passes most tests.

Anything you want to report failing?  Or are we calling this working now?

**Comment by rmjarvis** [comment] 2016-12-12 23:29
FYI, I added an item to the Installation FAQ about all this: [Why is SCons "Unable to build a python loadable module that uses tmv" using Anaconda?](https://github.com/GalSim-developers/GalSim/wiki/Installation-FAQ#why-is-scons-unable-to-build-a-python-loadable-module-that-uses-tmv-using-anaconda)

**Comment by esheldon** [comment] 2016-12-14 14:27
It turns out I spoke too soon. I had only run the tests from the /tests
directory

Most of the tests do complete if I use `run_all_tests`, which uses `../bin/installed_python`.

However, if I run using, e.g. `python test_base.py` I get a segfault.  This is
despite the fact that those pythons are the same.

Also I cannot import galsim
```
[esheldon@forest ~] python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import galsim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/__init__.py", line 94, in <module>
    from .position import PositionI, PositionD
  File "/home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/position.py", line 22, in <module>
    from . import _galsim
ImportError: /home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/_galsim.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
```


Here is the output from `run_all_tests`
```python
test_bandpass.py
test_base.py
test_bessel.py
test_calc.py
test_catalog.py
test_cdmodel.py
test_celestial.py
test_chromatic.py
test_compound.py
test_config_gsobject.py
test_config_image.py
test_config_noise.py
test_config_output.py
test_config_value.py
test_correlatednoise.py
test_deprecated.py
test_des.py
Traceback (most recent call last):
  File "test_des.py", line 23, in <module>
    import galsim
  File "/home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/__init__.py", line 94, in <module>
    from .position import PositionI, PositionD
  File "/home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/position.py", line 22, in <module>
    from . import _galsim
ImportError: /home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/_galsim.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
test_detectors.py
test_draw.py
test_fitsheader.py
test_hsm.py
test_image.py
test_inclined_exponential.py
test_integ.py
test_interpolatedimage.py
test_lensing.py
test_lsst.py
Traceback (most recent call last):
  File "test_lsst.py", line 24, in <module>
    import galsim
  File "/home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/__init__.py", line 94, in <module>
    from .position import PositionI, PositionD
  File "/home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/position.py", line 22, in <module>
    from . import _galsim
ImportError: /home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/_galsim.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
test_metacal.py
Traceback (most recent call last):
  File "test_metacal.py", line 22, in <module>
    import galsim
  File "/home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/__init__.py", line 94, in <module>
    from .position import PositionI, PositionD
  File "/home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/position.py", line 22, in <module>
    from . import _galsim
ImportError: /home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/_galsim.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
test_optics.py
test_phase_psf.py
test_photon_array.py
test_pse.py
test_random.py
test_randwalk.py
Traceback (most recent call last):
  File "test_randwalk.py", line 23, in <module>
    import galsim
  File "/home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/__init__.py", line 94, in <module>
    from .position import PositionI, PositionD
  File "/home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/position.py", line 22, in <module>
    from . import _galsim
ImportError: /home/esheldon/anaconda3/lib/python3.5/site-packages/galsim/_galsim.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
test_real.py
test_scene.py
test_sed.py
test_shapelet.py
test_shear.py
test_table.py
test_transforms.py
test_utilities.py
test_wcs.py
test_wfirst.py
```

**Comment by rmjarvis** [comment] 2016-12-14 17:00
I think you may be hitting the limits of the ability to cross-compile across gcc versions.  From what I've gathered, this seems to be a bug in gcc.  cf the following links:

http://stackoverflow.com/questions/35649772/undefined-reference-to-symbol-throw-out-of-range
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=745372

Here's another tack that might work.  What if you delete the libstdc++ (and similar) libraries in the anaconda directory and add symlinks to the ones in your gcc folder?  I think all the old APIs are included in the new files, so I *think* it wouldn't break any of the Anaconda linkages.  But it would prevent these problems from having two different stdc++ libraries.

Another idea: you could try copying out (or symlinking) the libpython.so file to another directory outside of the anaconda one and tell GalSim about that (with EXTRA_LIB_PATH).  Then when GalSim includes that directory for linking to libpython.so, it wouldn't also sweep in all the other kruft that Anaconda ships.

**Comment by rmjarvis** [comment] 2016-12-14 17:03
BTW, based on what you've written about importing galsim, I have no idea why run_all_tests would do anything sensible.

Unless...  maybe it's finding ../lib/_galsim.so rather than the installed one.  Did you remember to `scons install` GalSim?  Are these two libraries different?

**Comment by rmjarvis** [comment] 2016-12-14 17:05
Yep.  I think those ones that fail in your run_all_tests listing are the ones that import galsim normally rather than checking for an ImportError and adding '..' to the sys.path.  See if running `scons install` for GalSim makes things work.

**Comment by esheldon** [comment] 2016-12-14 17:09
Yeah, I did install everything, and those files are exactly the same.

As for why the tests might work, it seems that if `import galsim` fails, the tests load the local galsim package by modifying the path.  So that is a clue but a confusing one.

**Comment by esheldon** [comment] 2016-12-14 17:11
(looks like our messages with similar content passed one another)

**Comment by esheldon** [comment] 2016-12-15 13:16
I am able to successfully install and use galsim by installing miniconda instead of the full
anaconda.

I think the c++ libraries were included to support the python compilation in numba, which uses llvm.

So the procedure is

1. Install tmv in the standard way.
2. install miniconda http://conda.pydata.org/miniconda.html
3. Install basic packages needed for galsim `conda install future numpy astropy`
4. Install galsim in the usual way, specifying `TMV_DIR`

**Comment by rmjarvis** [comment] 2016-12-15 15:25
OK.  I updated the [FAQ entry](https://github.com/GalSim-developers/GalSim/wiki/Installation-FAQ#why-is-scons-unable-to-build-a-python-loadable-module-that-uses-tmv-using-anaconda).  OK to close this now?

**Closed** 2016-12-19 19:11 UTC
Labels: bug report, build
