### ISSUE TITLE
Bug in des_meds

### ISSUE THREAD

**Issue by ckrawiec** [GalSim-developers/GalSim#654] opened 2015-03-19 18:43 UTC
Hi All,

I'm attempting to use the des_meds module in galsim.des to write a MEDS file using galsim images. To do this, I tried to create a MultiExposureObject as follows:

```
gal = galsim.Gaussian(flux=1.e5,sigma=2.)
psf = galsim.Gaussian(flux=1., sigma=0.2)
final = galsim.Convolve([gal,psf])
image = galsim.ImageF(48,48,scale=0.2)
final.drawImage(image)
obj = des_meds.MultiExposureObject([image])
```

which gives me this error:

```
in __init__(self, images, weights, badpix, segs, wcs, id)
    135         else:
    136             # Get the wcs from the images.  Probably just the pixel scale.
--> 137             self.wcs = [ im.wcs.jacobian().setOrigin(im.trueCenter()) for im in self.images ]
    138 
    139          # check if weights,segs,jacks are lists

AttributeError: 'JacobianWCS' object has no attribute 'setOrigin'
```

which seems to be a problem outside of my grasp. Thanks for your help.

-Christina (grad student at UPenn)

**Comment by rmjarvis** [comment] 2015-03-19 20:00
Thanks for reporting this, Christina.

The proximate problem here is that `setOrigin` should be `withOrigin`.  

But this raises the larger issue that we don't actually have any unit tests of the des module.  Well, we do, but it is in the galsim/des directory rather than in our regular test directory, which means that it doesn't get run regularly.  And running it now, it seems to have other problems as well.

So I propose that we move that test to the main test directory and beef it up so it actually constitutes a fairly complete unit test of the code in the des module to keep the code here from getting out of date with any future changes in GalSim syntax or functionality.

**Comment by rmandelb** [comment] 2015-03-19 20:07
+1 for that, Mike.  Even as a non-user of that module, I'm happy to have the unit tests run as part of the standard set of unit tests so that it reminds us to keep it up to date.

**Comment by rmjarvis** [comment] 2016-01-06 01:18
@beckermr: I have two examples of making stamps with blends on this branch.
See [blend.yaml](https://github.com/GalSim-developers/GalSim/tree/%23654/examples/des/blend.yaml) and [blendset.yaml](https://github.com/GalSim-developers/GalSim/tree/%23654/examples/des/blendset.yaml).

The first (blend.yaml) is the simpler of the two.  It just draws multiple objects on each stamp, but only one is the primary (centered) object, and we don't try to put the neighbors also in the center of some other postage stamp.  But it does do the thing you wanted where a second output file is made that has the neighbor flux subtracted off.  So simulating the output of a perfect deblender.

The second one (blendset.yaml) is more complicated.  It puts each object in the center of a postage stamp.  So if a blend has 3 objects, there will be 3 corresponding postage stamps, with each object in the center of one.  Also, it outputs both the regular blended images and the perfect deblended images as MEDS files and uses real galaxies and PSFEx psfs.  (The other uses parametric profiles.)  There is a second run that does the same thing but outputs to a Tiled image to make it easier to view quickly in ds9.

The custom code for this is in [blend.py](https://github.com/GalSim-developers/GalSim/tree/%23654/examples/des/blend.py), so that should give you a start at seeing how custom types work in the GalSim config processing.  

I still need to write up good documentation for it, but these examples were useful, since I found a few bugs and added a couple extra hooks that I wanted here, but hadn't thought to add before.

**Comment by rmandelb** [comment] 2016-01-06 01:20
Would these be useful for DESC deblending studies too?

**Comment by rmjarvis** [comment] 2016-01-06 01:21
Here is a screen shot from the second one.  You can see the same grouping move around among the stamps as each galaxy is centered on a stamp.  And it's hard to tell from the image, but the noise realization is identical for each group.

<img width="1409" alt="blend" src="https://cloud.githubusercontent.com/assets/623887/12132452/9ea8e5b2-b3e9-11e5-95c6-7ead246a813f.png">

**Comment by rmjarvis** [comment] 2016-01-06 01:24
> Would these be useful for DESC deblending studies too?

Maybe.  I did this as a specific request for Matt, since he was asking me about the flexibility of the new config apparatus.  This is very close to a sim that he was doing with his Egret code.  He said if this simulation is possible with GalSim config files, then he would just switch to this, rather than continue to try to port in features that we already have here into Egret.

**Comment by rmjarvis** [comment] 2016-01-06 23:23
I think this branch is ready for PR.  I added a bunch of unit tests for the des module in addition to these extra config examples.  I also handled #602 here, since that was for a particular DES FITS image, although the issue is probably applicable more broadly.  Once "#691" is merged, I'll submit this for PR.

**Comment by beckermr** [comment] 2016-01-07 00:06
Wow this looks great! Thanks! I have a few questions.

1. I am curious about the handling of the noise fields. When I imagined doing this, I figured each HST cutout image would have a slightly different noise variance (after PSF convolution and whitening). Thus I figured that the first thing that had to be done after building the full image of blends would be to apply a slightly different noise to each location (depending on how many stamps overlapped there and their individual noise variance) in order to bring the total noise level up to some constant across the full image. Then after this, one would want to add in enough extra noise to match the desired observing conditions. Does the code do this? Or maybe the HST noise is small enough that this detail doesn't matter? (BTW, for real galaxies, this limits the noise matching on the unblended images since one does not have the exact noise realization of the neighbor stamp without the galaxy in it.)

2. I also did not understand the step of adding all of the profiles and then whitening based on the total noise field. I had assumed as a above that each object would be whitened individually. In other words, noise whitening based on a noise field that is a sum of the individual noise fields makes sense if everywhere in the image, all stamps contribute. However, I don't think this has to be the case.

3. How are the PSFs set for each object in the blend? It appears they are they same for each object. This is a really good default. I just want to make sure I am understanding the config parser correctly. 

@rmandelb I am not involved in the DESC blending stuff and so don't know where they are at with sims like this. I have personally found this setup to be very useful for testing code that tries to fit multiple objects in the stamps. Basically, with the 'unblended' files, you can get an estimate of the parameters of the object without neighbors, but subject to an almost identical noise field. Otherwise, I found for my simple sims with Egret, that it was hard to tell on an individual object if the multiple object fit failed or it it was noise when comparing to true, noise-less parameters.

**Comment by beckermr** [comment] 2016-01-07 00:30
I changed my comments above. I had confused the blend and blendset stamp builders.

**Comment by beckermr** [comment] 2016-01-07 00:42
I also did not understand the indexing. If obj_num is always increasing and the main object is built last, then how is `k = config['obj_num'] - config['blend_first']` greater than zero?

**Comment by rmjarvis** [comment] 2016-01-07 00:55
The code currently assumes that the RealGalaxy images are large enough to cover the full extend of the blended postage stamp.  You could certainly do something more sophisticated to make sure that they do in fact cover the whole area (by using `noise_pad_size`) or to keep track of the extent of each postage stamp on the larger image and whitening each region separately.  Probably the first option would be easier.

But these enhancements wouldn't require any changes to the overall config structure.  The point of this exercise from my perspective was to make sure that the hooks I put into the config parser were sufficient to handle this kind of simulation.  Please do feel free to take this as a straw man and improve upon it.  :)

And yes, the current hooks use a single PSF for everything in a single stamp.  If you wanted a variable PSF within a branch, I suppose that would be doable.  But currently, the code parses the `psf` field prior to calling the code to build the "Profile" (which is multiple profiles in this case).  This is what the `psf` argument is for `ProfileBlend`, which we use for all the profiles in the blend.  So to get a variable PSF I guess you'd have to do some custom parsing of the psf field within the Profile function.

**Comment by rmjarvis** [comment] 2016-01-07 00:59
> I also did not understand the indexing. If obj_num is always increasing and the main object is built last, then how is k = config['obj_num'] - config['blend_first'] greater than zero?

'obj_num' increases with each stamp.  Normally, that means each object, but in this case, several objects are build using the same `obj_num` index.  

We build all the objects in the blend when we are at the first stamp in the set.  So when 'obj_num == blend_first', we used that random number generator to build all the objects in the blend.  After that, for the next n_neighbors stamps, we don't regenerate any profiles, since they are all built already.  We just grab a different cutout from the cached image.

**Comment by beckermr** [comment] 2016-01-07 01:29
Makes sense. Thanks Mike!

**Closed** 2016-03-24 14:12 UTC
Labels: bug report, module
