### ISSUE TITLE
SED.wave_list doesn't redshift

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#520] opened 2014-03-31 18:09 UTC
Looks like I missed a bug in SED.py.
Here's an example:
```
import galsim
a=galsim.SED("path_to_GalSim/examples/data/CWW_E_ext.sed")
a=a.atRedshift(0.1)
a=a.thin(rel_err=1e-5)
```
gives
```ERROR:astropy:ValueError: Wavelength (128.0) is bluer than SED blue limit (140.8)```
The reason is that redshifting doesn't alter the .wave_list attribute.
This is an easy fix: two lines in SED.py:atRedshift():
```
if len(ret.wave_list) > 0:
    ret.wave_list *= wave_factor
```

Additionally, I think we should add a roundoff error guard to `SED.__init__()` similar to what's in `Bandpass.__init__()`:

```
        if len(self.wave_list) > 0.0:
            self.wave_list[0] = self.wave_list[0] + 0.0000001
            self.wave_list[-1] = self.wave_list[-1] - 0.0000001
```

This stops LookupTable from complaining when floating point roundoff leads to self.wave_list[0] > (self.wave_list[0] * factor) / factor, which is effectively how the SED class deals with redshifts and units.  It's definitely a hack though, so if anybody has a more elegant solution I'd love to hear it.

**Comment by shobhit16** [comment] 2016-06-15 19:47
Facing a similar issue when drawing an image (#16) of a galaxy (parametric, chromatic) from the 'COSMOS_25.2_training_sample' using the 'LSST_r filter'.

`Traceback (most recent call last):
  File "hsm_cosmos.py", line 401, in <module>
    main(sys.argv)
  File "hsm_cosmos.py", line 265, in main
    final_lsst.drawImage(filter_lsst['r'], image=im_lsst, scale=pixel_scale)
  File "/usr/local/lib/python2.7/site-packages/galsim/chromatic.py", line 1998, in drawImage
    wmult, integrator, self.gsparams)
  File "/usr/local/lib/python2.7/site-packages/galsim/utilities.py", line 757, in __call__
    result = self.user_function(*key)
  File "/usr/local/lib/python2.7/site-packages/galsim/chromatic.py", line 1794, in _get_effective_prof
    galsim.LookupTable(wave_list, bandpass(wave_list) * SED(wave_list),
  File "/usr/local/lib/python2.7/site-packages/galsim/chromatic.py", line 1782, in <lambda>
    SED = lambda w: reduce(lambda x,y:x*y, [s(w) for s in sep_SED], 1)
  File "/usr/local/lib/python2.7/site-packages/galsim/sed.py", line 209, in __call__
    .format(wmin, self.blue_limit))
ValueError: Requested wavelength (494.5) is bluer than blue_limit (605.4988873)`

Any ideas on how to resolve this?

**Comment by jmeyers314** [comment] 2016-06-15 20:16
Hi @shobhit16 , can you provide a minimal code snippet that reproduces the error?  I'm wondering if there's an unreasonable SED or redshift lurking somewhere.  It's hard to tell though without knowing what your code is trying to compute.

**Comment by shobhit16** [comment] 2016-06-15 20:41
Yes. Here's a reduced version of the code which should reproduce the problem. You would just need to point the line specifying the bandpass filter to the location of the filters on your computer.

`import numpy
import galsim


# Image Parameters
im_size = 64
pixel_scale = 0.05      # arcsec

# Reading the Catalog
cosmos_cat = galsim.COSMOSCatalog()
gal_hst = cosmos_cat.makeGalaxy(15, gal_type='parametric', chromatic = 'True')
# Flux Scaling for LSST
# ratio of (LSST diam)^2/(HST diam)^2
diam_sq_ratio = (8.4**2) / (2.4**2)
# exposure time of LSST in secs compared to 1 sec for HST
exp_time = 16
gal_lsst = gal_hst.withScaledFlux(flux_ratio=diam_sq_ratio * exp_time)

# LSST PSF (Parameters based on the lsst.yaml)
# Atmospheric Component (Type: Kolmogorov) (Chromatic)
fwhm = 0.67 # Value depends on wavelength of monochromatic PSF
# Constructing atmospheric PSF
base_atmos = galsim.Kolmogorov(fwhm=fwhm) # 500 nm
lsst_atmos = galsim.ChromaticAtmosphere(base_atmos, 500, zenith_angle=0 * galsim.degrees)
# Optical Component
lam = 700 # nanometers
diam = 8.4 # meters
lam_over_diam = 0.017 # (700 nm / 8.4 m) * 206265 = 0.017 arcsec
obscuration = 0.4  # linear obscuration (3.4m/8.4m = 0.4)
nstruts = 4  # number of supports
strut_thick = 0.03  # relative to dimeter (25cm in this case)
# Arbitrary, intentionally not aligned with the axis of the image
strut_angle = 10 * galsim.degrees
# Plausible Values of aberrations
# Using Noll Convention
aberrations = numpy.zeros(12)
aberrations[4] = 0.06 # index 4 (defocus)
aberrations[5] = 0.02 # index 5 (astig1)
aberrations[6] = -0.03 # index 6 (astig2)
aberrations[7] = 0.02 # index 7 (coma1)
aberrations[8] = -0.04 # index 8 (coma2)
# Defining a chromatic LSST PSF
lsst_optics = galsim.ChromaticOpticalPSF(lam = lam, diam = diam, aberrations = aberrations)

# Constructing the composite LSST PSF based on the optical and atmospheric components
psf_lsst = galsim.Convolve([lsst_atmos, lsst_optics])
    
# Reading the LSST filter ('r' in this case)
filter = galsim.Bandpass('/Users/apple/Git/GalSim/examples/data/LSST_r.dat')
filter = filter.thin(rel_err=1e-4)
        
# Final Image        
final_lsst = galsim.Convolve([psf_lsst, gal_lsst])

im_lsst = galsim.Image(im_size, im_size)
final_lsst.drawImage(filter, image=im_lsst, scale=pixel_scale)`

**Comment by shobhit16** [comment] 2016-06-15 20:46
Yes. Here's a reduced version of the code which should reproduce the problem. You would just need to point the line specifying the bandpass filter to the location of the filters on your computer.

```
import numpy
import galsim

# Image Parameters
im_size = 64
pixel_scale = 0.05      # arcsec

# Reading the Catalog
cosmos_cat = galsim.COSMOSCatalog()
gal_hst = cosmos_cat.makeGalaxy(15, gal_type='parametric', chromatic = 'True')
# Flux Scaling for LSST
# ratio of (LSST diam)^2/(HST diam)^2
diam_sq_ratio = (8.4**2) / (2.4**2)
# exposure time of LSST in secs compared to 1 sec for HST
exp_time = 16
gal_lsst = gal_hst.withScaledFlux(flux_ratio=diam_sq_ratio * exp_time)

# LSST PSF (Parameters based on the lsst.yaml)
# Atmospheric Component (Type: Kolmogorov) (Chromatic)
fwhm = 0.67 # Value depends on wavelength of monochromatic PSF
# Constructing atmospheric PSF
base_atmos = galsim.Kolmogorov(fwhm=fwhm) # 500 nm
lsst_atmos = galsim.ChromaticAtmosphere(base_atmos, 500, zenith_angle=0 * galsim.degrees)
# Optical Component
lam = 700 # nanometers
diam = 8.4 # meters
lam_over_diam = 0.017 # (700 nm / 8.4 m) * 206265 = 0.017 arcsec
obscuration = 0.4  # linear obscuration (3.4m/8.4m = 0.4)
nstruts = 4  # number of supports
strut_thick = 0.03  # relative to dimeter (25cm in this case)
# Arbitrary, intentionally not aligned with the axis of the image
strut_angle = 10 * galsim.degrees
# Plausible Values of aberrations
# Using Noll Convention
aberrations = numpy.zeros(12)
aberrations[4] = 0.06 # index 4 (defocus)
aberrations[5] = 0.02 # index 5 (astig1)
aberrations[6] = -0.03 # index 6 (astig2)
aberrations[7] = 0.02 # index 7 (coma1)
aberrations[8] = -0.04 # index 8 (coma2)
# Defining a chromatic LSST PSF
lsst_optics = galsim.ChromaticOpticalPSF(lam = lam, diam = diam, aberrations = aberrations)

# Constructing the composite LSST PSF based on the optical and atmospheric components
psf_lsst = galsim.Convolve([lsst_atmos, lsst_optics])
    
# Reading the LSST filter ('r' in this case)
filter = galsim.Bandpass('/Users/apple/Git/GalSim/examples/data/LSST_r.dat')
filter = filter.thin(rel_err=1e-4)
        
# Final Image        
final_lsst = galsim.Convolve([psf_lsst, gal_lsst])
im_lsst = galsim.Image(im_size, im_size)
final_lsst.drawImage(filter, image=im_lsst, scale=pixel_scale)
```

**Comment by rmandelb** [comment] 2016-06-15 20:47
@jmeyers314 , does this make you think of #745 ?

**Comment by rmandelb** [comment] 2016-06-15 20:49
Oy, didn't finish my thought.  My initial gut reaction was that it sounds like that.  @shobhit16 , can you confirm whether you're using the version of GalSim as of the current master branch?  Or is it possible that it's an earlier version, before the issue in #745 was fixed?

**Comment by shobhit16** [comment] 2016-06-15 21:07
@rmandelb Yes. It was the current master branch (GalSim 1.4 to be specific).

**Comment by rmandelb** [comment] 2016-06-15 21:11
OK, thanks for clarifying that it's the current master branch.  (GalSim v1.4 hasn't been tagged yet, so any commit after v1.3 was tagged will say v1.4, but this doesn't uniquely identify a commit, unlike "current master branch" or any version from 1.3 and earlier.)

**Comment by shobhit16** [comment] 2016-06-15 21:35
@rmandelb @jmeyers314 Ok. This sounds weird but I checked out the master again and recompiled it, which seems to eliminate the error.

**Comment by arunkannawadi** [comment] 2016-06-15 22:04
The error mentioned in #745 occurred while calling the makeGalaxy routine
while this error seemed to occur while drawing the image. So the source of
the errors were probably different. But it's good that the error no longer
occurs.
On Jun 15, 2016 2:35 PM, "Shobhit Sharma" <notifications@github.com> wrote:

@rmandelb <https://github.com/rmandelb> @jmeyers314
<https://github.com/jmeyers314> Ok. This sounds weird but I checked out the
master again and recompiled it, which seems to eliminate the error.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GalSim-developers/GalSim/issues/520#issuecomment-226327358>,
or mute the thread
<https://github.com/notifications/unsubscribe/AE3fHqkDwl0xTaz-_DEhltr7BaGnljJOks5qMHAfgaJpZM4BuWUB>
.

**Comment by cwwalter** [comment] 2016-06-15 22:06
@shobhit16 how long was it since you last did a 'git pull' on master?  Maybe some other bug fix has been merged since then.

**Comment by cwwalter** [comment] 2016-06-15 22:07
oops left off.. Or if you you checked it out separately, you can go back to the version where you had an error and look at the last commit hash and then see what has happened since then.

**Comment by jmeyers314** [comment] 2016-06-15 22:58
Hmmm...  Well, I can confirm that the script above runs fine for my copy of GalSim too.  My intuition is that it probably is related to #745, though as @arunkannawadi points out, the details do appear a bit different.  @shobhit16 , are you satisfied that we can re-close this?

**Comment by shobhit16** [comment] 2016-06-15 23:15
@jmeyers314 Yes!

**Closed** 2016-06-15 23:16 UTC
Labels: bug report
