### ISSUE TITLE
assert failure in galsim::OneDimensionalDeviate::shoot

### ISSUE THREAD

**Issue by jchiang87** [GalSim-developers/GalSim#881] opened 2017-04-04 19:37 UTC
I'm getting an assert failure when I run the attached code (and pickle files):
```
$ python galsim_test_case.py 
galsim.__version__: 1.4.3
python: src/OneDimensionalDeviate.cpp:328: boost::shared_ptr<galsim::PhotonArray> galsim::OneDimensionalDeviate::shoot(int, galsim::UniformDeviate) const: Assertion `N>=0' failed.
Aborted
$
```
In contrast to #866, I'm seeing this much more often: about 10% of the imsim jobs are dying with this error when I try to run using the Kolmogorov PSF implementation that we recently added.

[oneDimDeviate_assert_fail.zip](https://github.com/GalSim-developers/GalSim/files/894289/oneDimDeviate_assert_fail.zip)

**Comment by rmjarvis** [comment] 2017-04-04 23:37
Well, the problem here is that the number of photons to shoot is overflowing the size of int and wrapping around to negative values.

So this is clearly a bug, and we should catch this in the python layer rather than crash and burn with an assert failure.  But do you really intend to have something with flux = 3.97e9?  Here is the object being drawn:
```
galsim.Convolve(galsim.Kolmogorov(lam_over_r0=0.529987797134), galsim.Gaussian(sigma=0.171131263474)) * 3973131100.34
```

**Comment by jchiang87** [comment] 2017-04-04 23:43
This is a question for @danielsf perhaps.  The imsim code is simply getting the parameters for each object (stars in this case) from queries to the catsim db and then creating stars with those fluxes.  We aren't applying any magnitude limits on the stars that are simulated, so maybe that's warranted?   Or maybe those fluxes are not realistic even for the brightest stars in those catalogs, and there is a bug elsewhere.

**Comment by rmjarvis** [comment] 2017-04-04 23:43
BTW, I'll note that this is already fixed on master.  Now it emits a warning that it won't actually draw the object:
```
/Users/Mike/lib/python2.7/site-packages/galsim/gsobject.py:1810: UserWarning: Automatic n_photons calculation did not end up with positive N. (n_photons = -2147483648.0)  No photons will be shot. prof = galsim.Convolve(galsim.Kolmogorov(lam_over_r0=0.529987797134), galsim.Gaussian(sigma=0.171131263474)).expand(6.91359985819).shift(1410.64264865,349.447410634) * 83123613.715  flux = 3973131100.34  poisson_flux = True  max_extra_noise = 0.0  g = -0.540501582698  
  "g = %s  "%g)
```

**Comment by rmjarvis** [comment] 2017-04-04 23:45
Or perhaps "fixed" should be in scare quotes, since probably that's not really the right action either.  Probably the user wanted *something* drawn.  But at least it doesn't crash.

**Comment by rmjarvis** [comment] 2017-04-04 23:48
Also, if you do want to draw these, then probably you should switch to `method='fft'` if the flux is above some value.  Like 1.e6 or so.

**Comment by jchiang87** [comment] 2017-04-05 04:45
FWIW, my preference would be for an exception to be raised if the requested flux is so high that the number of photons would wrap to a negative value.  That would force me to switch to a method that would draw the flux I asked for (or otherwise handle that exception), as well as alert me to consider whether that flux even makes sense.

**Comment by rmjarvis** [comment] 2017-04-05 05:12
I agree.  If the flux is positive, but the number of photons ends up negative, that should raise an error along the lines of "Cannot draw with photon shooting" and explain why.

Also, just to clarify, it turns out the problem is not Python int overflowing (which happens at a much larger value than this).  Rather, it is the boost Poisson RNG hitting its maximum, which must use a 32 bit integer internally.  So another option to avoid this for now would be to set poisson_flux=False.

**Comment by rmjarvis** [comment] 2017-04-05 06:48
I fixed this slightly differently.  Since it's just a problem with the poisson deviate for very large mean, I just have it use a Gaussian deviate instead in that case, since that's very close to the same distribution.  So it will go ahead and do the photon shooting you requested and not throw an exception.

However, I think you should put in some checks related to the flux, since you might not actually want to draw these objects.  It took my laptop 12 minutes (!) to draw the object in your test case.  If this kind of object is extremely rare, maybe that's ok.  But you should at least flag them up somewhere so you can check if these fluxes are actually correct.

**Comment by rmjarvis** [comment] 2017-04-05 06:49
cross reference PR #882

**Closed** 2017-04-16 03:16 UTC
Labels: bug report, critical, numerics
